apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-user-nginx
  annotations:
    kubernetes.io/change-cause: version 1.20
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: user-nginx
          image: nginx:1.20
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%