apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - image: luksa/fortune
      name: fortune
      volumeMounts:
        - mountPath: /var/htdocs
          name: docs
    - image: nginx
      name: web-server
      volumeMounts:
        - name: docs
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
  volumes:
    - name: docs
      emptyDir:
        sizeLimit: 500Mi