apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  type: ClusterIP
  # clusterIP: 10.100.100.100
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80