apiVersion: v1
kind: Pod
metadata:
  name: user-nginx
spec:
  containers:
    - image: nginx:latest
      name: user-nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1
          memory: 128Mi